// eslint-disable-next-line import/extensions
import { sortByNameFunction } from '../functions';
import { DataItemTypeEnum, IShapeItem, IShapeItemGroup, ShapeTypeEnum } from '../models';
import { IMPORTED_SHAPES } from './imported-shapes';

export const USER_SHAPE_DELETE_MODE = 'builder-user-shape-delete-mode';
export const USER_SHAPE_DELETE_ITEM = 'builder-user-shape-delete-item';

const GEOMETRY_SHAPES: IShapeItemGroup[] = [
  {
    name: 'common',
    shapes: [
      {
        name: 'Square',
        tooltipLabel: 'square',
        shape: 'whiteSpace=wrap;html=1;aspect=fixed;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Квадрат Square مربع square',
      },
      {
        name: 'Rectangle',
        tooltipLabel: 'rectangle',
        shape: 'rounded=0;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 60,
        searchLabel: 'Прямоугольник Rectangle مستطیل rectangle',
      },
      {
        name: 'Rectangle Round',
        tooltipLabel: 'rectangleRound',
        shape: 'rounded=1;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 60,
        searchLabel: 'Прямоугольник скругленный Rounded Rectangle مستطیل گرد rectangleRound',
      },
      {
        name: 'Parallelogram',
        tooltipLabel: 'parallelogram',
        shape: 'shape=parallelogram;perimeter=parallelogramPerimeter;whiteSpace=wrap;html=1;fixedSize=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 60,
        searchLabel: 'Параллелограм Parallelogram متوازی الاضلاع parallelogram',
      },
      {
        name: 'Trapezoid',
        tooltipLabel: 'trapezoid',
        shape: 'shape=trapezoid;perimeter=trapezoidPerimeter;whiteSpace=wrap;html=1;fixedSize=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 60,
        searchLabel: 'Трапеция Trapezoid ذوزنقه trapezoid',
      },
      {
        name: 'Step',
        tooltipLabel: 'polygon',
        shape: 'shape=step;perimeter=stepPerimeter;whiteSpace=wrap;html=1;fixedSize=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Process',
        tooltipLabel: 'rectangle',
        shape: 'shape=process;whiteSpace=wrap;html=1;backgroundOutline=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 60,
        searchLabel: 'Прямоугольник Rectangle مستطیل rectangle',
      },
      {
        name: 'Cube',
        tooltipLabel: 'cube',
        shape: 'shape=cube;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;darkOpacity=0.05;darkOpacity2=0.1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Куб Cube مکعب cube',
      },
      {
        name: 'Manual Input',
        tooltipLabel: 'polygon',
        shape: 'shape=manualInput;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Loop Limit',
        tooltipLabel: 'polygon',
        shape: 'shape=loopLimit;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 100,
        height: 80,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Off Page Connector',
        tooltipLabel: 'polygon',
        shape: 'shape=offPageConnector;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Delay',
        tooltipLabel: 'tag',
        shape: 'shape=delay;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 40,
        searchLabel: 'Тег Tag برچسب tag',
      },
      {
        name: 'Display',
        tooltipLabel: 'tag',
        shape: 'shape=display;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 40,
        searchLabel: 'Тег Tag برچسب tag',
      },
      {
        name: 'Triangle',
        tooltipLabel: 'triangle',
        shape: 'shape=triangle;whiteSpace=wrap;html=1;perimeter=trianglePerimeter;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 80,
        searchLabel: 'Треугольник Triangle مثلث triangle',
      },
      {
        name: 'Rhombus',
        tooltipLabel: 'rhombus',
        shape: 'shape=rhombus;perimeter=rhombusPerimeter;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Ромб Rhombus لوزی rhombus',
      },
      {
        name: 'Hexagon',
        tooltipLabel: 'hexagon',
        shape: 'shape=hexagon;perimeter=hexagonPerimeter2;whiteSpace=wrap;html=1;fixedSize=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Шестиугольник Hexagon شش ضلعی hexagon',
      },
      {
        name: 'Sort',
        tooltipLabel: 'rhombus',
        shape: 'shape=sortShape;perimeter=rhombusPerimeter;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Ромб Rhombus لوزی rhombus',
      },
      {
        name: 'Collate',
        tooltipLabel: 'polygon',
        shape: 'shape=collate;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Switch',
        tooltipLabel: 'polygon',
        shape: 'shape=switch;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 60,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Circle',
        tooltipLabel: 'circle',
        shape: 'shape=ellipse;whiteSpace=wrap;html=1;aspect=fixed;perimeter=ellipsePerimeter;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Ellipse',
        tooltipLabel: 'ellipse',
        shape: 'shape=ellipse;whiteSpace=wrap;html=1;perimeter=ellipsePerimeter;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Эллипс Ellipse بیضی ellipse',
      },
      {
        name: 'Cylinder',
        tooltipLabel: 'cylinder',
        shape: 'shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;size=15;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 80,
        searchLabel: 'Цилиндр Cylinder سیلندر cylinder',
      },
      {
        name: 'Data Store',
        tooltipLabel: 'cylinder',
        shape: 'shape=datastore;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 60,
        searchLabel: 'Цилиндр Cylinder سیلندر cylinder',
      },
      {
        name: 'Tape Data',
        tooltipLabel: 'circle',
        shape: 'shape=tapeData;whiteSpace=wrap;html=1;perimeter=ellipsePerimeter;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Ellipse',
        tooltipLabel: 'circle',
        shape: 'shape=orEllipse;perimeter=ellipsePerimeter;whiteSpace=wrap;html=1;backgroundOutline=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Ellipse',
        tooltipLabel: 'circle',
        shape: 'shape=sumEllipse;perimeter=ellipsePerimeter;whiteSpace=wrap;html=1;backgroundOutline=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Ellipse',
        tooltipLabel: 'circle',
        shape: 'shape=lineEllipse;perimeter=ellipsePerimeter;whiteSpace=wrap;html=1;backgroundOutline=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Ellipse',
        tooltipLabel: 'circle',
        shape: 'shape=lineEllipse;line=vertical;perimeter=ellipsePerimeter;whiteSpace=wrap;html=1;backgroundOutline=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Internal Storage',
        tooltipLabel: 'square',
        shape: 'shape=internalStorage;whiteSpace=wrap;html=1;backgroundOutline=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Квадрат Square مربع square',
      },
      {
        name: 'Tape',
        tooltipLabel: 'circle',
        shape: 'shape=tape;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 100,
        searchLabel: 'Круг Circle دایره circle',
      },
      {
        name: 'Document',
        tooltipLabel: 'document',
        shape: 'shape=document;whiteSpace=wrap;html=1;boundedLbl=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Документ Document مدرک document',
      },
      {
        name: 'Note',
        tooltipLabel: 'note',
        shape: 'shape=note;whiteSpace=wrap;html=1;backgroundOutline=1;darkOpacity=0.05;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 100,
        searchLabel: 'Заметка Note یادداشت note',
      },
      {
        name: 'Card',
        tooltipLabel: 'card',
        shape: 'shape=card;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 100,
        searchLabel: 'Карточка Card کارت card',
      },
      {
        name: 'Callout',
        tooltipLabel: 'callout',
        shape: 'shape=callout;whiteSpace=wrap;html=1;perimeter=calloutPerimeter;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Сообщение Callout پیام callout',
      },
      {
        name: 'Cross',
        tooltipLabel: 'cross',
        shape: 'shape=cross;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Крест Cross صلیب cross',
      },
      {
        name: 'Corner',
        tooltipLabel: 'corner',
        shape: 'shape=corner;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Угл Corner گوشه corner',
      },
      {
        name: 'Tee',
        tooltipLabel: 'corner',
        shape: 'shape=tee;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 80,
        height: 80,
        searchLabel: 'Угл Corner گوشه corner',
      },
      {
        name: 'Cloud',
        tooltipLabel: 'cloud',
        shape: 'ellipse;shape=cloud;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 120,
        height: 80,
        searchLabel: 'Облако Cloud ابر cloud',
      },
      {
        name: 'Actor',
        tooltipLabel: 'actor',
        shape: 'shape=umlActor;verticalLabelPosition=bottom;verticalAlign=top;html=1;outlineConnect=0;',
        cellType: ShapeTypeEnum.Geometry,
        width: 30,
        height: 60,
        searchLabel: 'Человек Actor شخص actor',
      },
      {
        name: 'User',
        tooltipLabel: 'actor',
        shape: 'shape=actor;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 40,
        height: 60,
        searchLabel: 'Человек Actor شخص actor',
      },
      {
        name: 'Xor',
        tooltipLabel: 'xor',
        shape: 'shape=xor;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 80,
        searchLabel: 'Исключающее ИЛИ XOR یا انحصاری xor',
      },
      {
        name: 'Or',
        tooltipLabel: 'or',
        shape: 'shape=or;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 80,
        searchLabel: 'Логическое ИЛИ OR یا منطقی or',
      },
      {
        name: 'Data Storage',
        tooltipLabel: 'polygon',
        shape: 'shape=dataStorage;whiteSpace=wrap;html=1;fixedSize=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 100,
        height: 80,
        searchLabel: 'Многоугольник Polygon چندضلعی polygon',
      },
      {
        name: 'Text',
        tooltipLabel: 'text',
        shape:
          'text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 60,
        showLabel: true,
        searchLabel: 'Текст Text متن text',
      },
      {
        name: 'Text',
        tooltipLabel: 'text',
        value: '<h1>Заголовок</h1><p>Содержание</p>',
        shape:
          'text;html=1;strokeColor=none;fillColor=none;spacing=5;spacingTop=-20;whiteSpace=wrap;overflow=hidden;rounded=0;',
        cellType: ShapeTypeEnum.HtmlShape,
        width: 120,
        height: 120,
        showLabel: true,
        searchLabel: 'Текст Text متن text',
      },
    ],
  },
  {
    name: 'arrows',
    shapes: [
      {
        name: 'Arrow Up',
        tooltipLabel: 'arrow',
        shape: 'shape=singleArrow;direction=north;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 100,
        searchLabel: 'Укзатель Arrow فلش arrow',
      },
      {
        name: 'Arrow Down',
        tooltipLabel: 'arrow',
        shape: 'shape=singleArrow;direction=south;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 100,
        searchLabel: 'Укзатель Arrow فلش arrow',
      },
      {
        name: 'Arrow Right',
        tooltipLabel: 'arrow',
        shape: 'shape=singleArrow;direction=east;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 100,
        height: 60,
        searchLabel: 'Укзатель Arrow فلش arrow',
      },
      {
        name: 'Arrow Left',
        tooltipLabel: 'arrow',
        shape: 'shape=singleArrow;direction=west;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 100,
        height: 60,
        searchLabel: 'Укзатель Arrow فلش arrow',
      },
      {
        name: 'Arrow Vertical',
        tooltipLabel: 'arrow',
        shape: 'shape=doubleArrow;direction=south;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 60,
        height: 100,
        searchLabel: 'Укзатель Arrow فلش arrow',
      },
      {
        name: 'Arrow Horizontal',
        tooltipLabel: 'arrow',
        shape: 'shape=doubleArrow;whiteSpace=wrap;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 100,
        height: 60,
        searchLabel: 'Укзатель Arrow فلش arrow',
      },
      {
        name: 'Bidirectional Arrow',
        tooltipLabel: 'biDirectConnector',
        shape: 'shape=flexArrow;endArrow=classic;startArrow=classic;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель двухсторонний Bi-Directional Connector اتصال‌دهنده دوطرفه biDirectConnector',
      },
      {
        name: 'Arrow',
        tooltipLabel: 'directConnector',
        shape: 'shape=flexArrow;endArrow=classic;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель направленный Directed Connector اتصال‌دهنده مستقیم directConnector',
      },
      {
        name: 'Dashed Line',
        tooltipLabel: 'nonDirectConnector',
        shape: 'endArrow=none;dashed=1;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель ненаправленный Non-Directed Connector اتصال‌دهنده غیرمستقیم nonDirectConnector',
      },
      {
        name: 'Dotted Line',
        tooltipLabel: 'nonDirectConnector',
        shape: 'endArrow=none;dashed=1;html=1;dashPattern=1 3;strokeWidth=2;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель ненаправленный Non-Directed Connector اتصال‌دهنده غیرمستقیم nonDirectConnector',
      },
      {
        name: 'Line',
        tooltipLabel: 'nonDirectConnector',
        shape: 'endArrow=none;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель ненаправленный Non-Directed Connector اتصال‌دهنده غیرمستقیم nonDirectConnector',
      },
      {
        name: 'Bidirectional Connector',
        tooltipLabel: 'biDirectConnector',
        shape: 'endArrow=classic;startArrow=classic;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель двухсторонний Bi-Directional Connector اتصال‌دهنده دوطرفه biDirectConnector',
      },
      {
        name: 'Directional Connector',
        tooltipLabel: 'directConnector',
        shape: 'endArrow=classic;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 50,
        height: 50,
        isEdge: true,
        searchLabel: 'Соединитель направленный Directed Connector اتصال‌دهنده مستقیم directConnector',
      },
      {
        name: 'Link',
        tooltipLabel: 'link',
        shape: 'shape=link;html=1;',
        cellType: ShapeTypeEnum.Geometry,
        width: 100,
        height: 0,
        isEdge: true,
        searchLabel: 'Соединитель Link لینک link',
      },
    ],
  },
  {
    name: 'tables',
    shapes: [
      {
        name: 'list',
        shape: 'text;strokeColor=none;fillColor=none;html=1;whiteSpace=wrap;verticalAlign=middle;overflow=hidden;',
        cellType: ShapeTypeEnum.HtmlShape,
        value: '<ul><li>Значение 1</li><li>Значение 2</li><li>Значение 3</li></ul>',
        width: 100,
        height: 40,
        showLabel: false,
        searchLabel: 'Список List لیست list',
      },
      {
        name: 'list',
        shape: 'text;strokeColor=none;fillColor=none;html=1;whiteSpace=wrap;verticalAlign=middle;overflow=hidden;',
        cellType: ShapeTypeEnum.HtmlShape,
        value: '<ol><li>Значение 1</li><li>Значение 2</li><li>Значение 3</li></ol>',
        width: 100,
        height: 40,
        showLabel: false,
        searchLabel: 'Список List لیست list',
      },
      {
        name: 'table',
        shape:
          '7ZjJTsMwEIafJleUhZZybVgucAFewDTT2pLjiewpaXl6xolLVQFqWBJArZRKns2xv5H7y4myvFxdW1HJWyxAR9lllOUWkdpRucpB6yiNVRFlF1GaxvyL0qsPokkTjSthwVCXgrQteBJ6Ca2ndTha6+BwUlR+SOLRu6aSSl7mRcLDWiqC+0rMfLzmTbDPkbB0r569K2Z7hoaEMmBDzQy1FpVTzWRthlS6uBFrXNLmNRtrGpYHlmD14RYbV9jfNWAJZNecUquCZMiYtBhiCWohN2WBTSxc61i81m6J8SBAex9g1h0gL5mU0HcwI2EWXVi+ZVVYrB6EXQAFR4XKENjLJ6bhgm+utM5Ro0du0PgXEVYhqGG+qX1EIiyDYQOY10kbKKMpP4wpj09G0Yh3k7OdbG1+fLqlHI0jy432c4BwVIPr3MD0aw08/YH+nfbbP2N89rZ/324NMsq5xppNqYoCTFfG2V7G454Qjw4c8WoX7wDEx0fiO3/wAyA/O+pAbzqw3m3TELIwOZQTdPZrsnB+4IiHl4UkPiIfWheS5CgMfQvDZEBhSD5xY/7fZyjZf63u7dD0fKv++5B/QRwO5ia8h3mP6sDm9tNeE9v58vcC',
        cellType: ShapeTypeEnum.DataShape,
        width: 180,
        height: 120,
        searchLabel: 'Таблица Table میز table',
      },
      {
        name: 'table',
        shape:
          '7ZjBbqMwEIafhmuFISTptbTbS/eyrfbuBie2ZDzITEqyT79jMMlGWVTUBlqVSkTyjGeM+SbDLxPEab67t7yQPyETOojvgji1ANiM8l0qtA6iUGVBfBtEUUi/IPrRMcvq2bDgVhjskxA1CS9cb0XjaRwl7rV3lJIXboj82bluJOa0zVtGw0oqFI8FX7n5ih6CfCVyi4/qj3OFZK/AIFdGWJ+zAq15Uap6sSZCKp098D1ssb1Na7nobW4eKL/00Raqf02/f2FR7DoZ1C4P4F5ALtDuKaRSGUofsWw4hVKojWzTPLyQl41jc8g9IqWBp/p/wnF/wrRlVFz/EivkZtMH9jnMzELxxO1GoHcUoAwKe/dCNFpoa6V1ChpcTQwYdyOEwk9qsW5znwER8ha8B3NYtIaS3NBFmNLwKgkSepqUbHa06XLhFlMwJVr6J7g1BC+xEiX2LWD0tgLOLlC/2Vn9ftfDKGQXLaQxLvpYyHfXCIjpWkNFplRZJkxf2PGrsOcDsU46WV+2aT49690p5xHQzzvRx5NEf3j3j8B+8S0Rg0nE/rRMYyjGsrOVZl+0lRYfphjXnayTabEeXzFY2Ml+Pkn2Y0oGY9+aMbRmLEfUDHZ+EG+bafFFm4m9fiofrHvOD+Ut7eXEaH+AbnSfqK+nCX9A4SDz+DGxnjv51vgX',
        cellType: ShapeTypeEnum.DataShape,
        width: 180,
        height: 120,
        searchLabel: 'Таблица Table میز table',
      },
      {
        name: 'table',
        shape:
          '7ZhRb6MwDMc/Da8nAmPdvZbu9nJ7WfcFMnAhUohR4o12n34OpKumrmqlDXa6VqJS/Lcdkp8bWSFK82Z9Z2Vb32MJOkpvozS3iDSMmnUOWkdJrMooXURJEvMvSv4c8IreG7fSgqFTEpIh4UXqZxiUR/mkYVAdbXRQXS1bP6Tem85ranitC8HDrlYEy1YW3t/xTlhzJC0t1auX0piFAg1JZcCGpAK1lq1T/WyLPqJWuvwrN/hM2/dsrfmKs5dhMT5balUZHhe8Sz/lPOwCLMH6IIleChjuABsgu+GQTpVUh4ibgVZcg6rqbVoWROkGoXrP3YHlQWD7Oed0j/NBxLxkUlI/QEHSVKfQ3odZWmwfpa2AgtCi8qhuX5iGC9pKaZ2jRl8Tg8a/iLANTg2rbe4TEmETDBvAvE/aQ8nm/DCmPP6VRRnvJmdb7Gx+fLilHI0jy/8EPwdIRx04OrWAyecF3ATEoUzH6nn1DeW8GrecxvjoXTm/XClksiuNHZu1KkswpyJPj56Z65EQZ2eOeP0R7wTEry/E+4RkOuSzS1sYuy3MJmwLN+dygmY/1hZ+nzni6duCiC/Ip+4LQlwaw9iNQYgJO4PYv2j/p4dIHL9mj3ZqRr5l//uQf6A7nM1V+AjzEdsDm7svgr3vwwfDNw==',
        cellType: ShapeTypeEnum.DataShape,
        width: 180,
        height: 120,
        searchLabel: 'Таблица Table میز table',
      },
      {
        name: 'table',
        shape:
          '7Zhdb5swFIZ/DbcTHyVrbiFdb7Kbptq9Cw5YMj7IPi1kv37HYJK1FDWbQoOmSUSyz4dt3id+L/CitGrvNavL75Bz6UV3XpRqAOxHVZtyKb3QF7kXbbww9Onnhd8mskGX9WumucJzGsK+4YXJZ95HHtmT5H3U4EG6qClZbYfYZaOkxIrOuglo2JQC+a5mmc039CYUM8g07sRPG4p8CmSgkAnFtWvKQEpWG9GttukqSiHzLTvAMw77DLNkL1qeP0BjXLeGZkuLGde6p8V37qw2zaQoFI0zEsHumLiX5Bp5OylUF3Iq3XOoOOoDlTQix9JV3PZi+iUXRTm0xS7ITB8ojr0n3WngpH8fQzTCMEmAjoyCyQeeIVPFOTDGWuca6kemC44uUIOwUt29kBpHVYWUKUiwyBQouxFC7ZKS74feJ0CEaiDjhDku2okSJ/SQTKn/JfZiepuU5sFpTo8t15iCMqjpj2LX4Mxgww2eCzB8H+DBSewwfcQzugDOmxHO4KI8lbLVJ55/jMp/gwpI2r2EhqalyHOuztU8+vDS3MykcTzS+Ec3DP2Faz24U1+bGNpQqGLbd65mgNG+BvH7BZgLzupf8LO34JblZ6tP9LOvI5yX5bkcP1tdzc9uJ/1s4VrP52cTMK7gZ+v/fja3n60/0c8Cf8QzWvYl++s7tL6aoQXBpKMtXOz5HG2CxvyORtPTR4Uu9+qbwy8=',
        cellType: ShapeTypeEnum.DataShape,
        width: 180,
        height: 120,
        searchLabel: 'Таблица Table میز table',
      },
      {
        name: 'tableHtml',
        shape:
          'text;html=1;strokeColor=#c0c0c0;fillColor=var(--color-text-main-and-axis-labels);overflow=fill;rounded=0;',
        cellType: ShapeTypeEnum.HtmlShape,
        value:
          '<table border="1" width="100%" height="100%" cellpadding="4" style="width:100%;height:100%;border-collapse:collapse;"><tr style="background-color:var(--color-background-main);color:var(--color-text-main-and-axis-labels);border:1px solid var(--color-borders-and-icons-stroke-shape);"><th>Заголовок 1</th><th>Заголовок 2</th><th>Заголовок 3</th></tr><tr style="background-color:var(--color-background-widget-headers);border:1px solid var(--color-borders-and-icons-widget-strokes);"><td>Значение 1</td><td>Значение 2</td><td>Значение 3</td></tr>',
        width: 280,
        height: 80,
        searchLabel: 'HTML таблица HTML Table جدول HTML tableHtml',
      },
      {
        name: 'tableHtml',
        shape:
          'text;html=1;strokeColor=#c0c0c0;fillColor=var(--color-text-main-and-axis-labels);overflow=fill;rounded=0;',
        cellType: ShapeTypeEnum.HtmlShape,
        value:
          '<table border="1" width="100%" height="100%" cellpadding="4" style="width:100%;height:100%;border-collapse:collapse;"><tr style="background-color:var(--color-background-main);color:var(--color-text-main-and-axis-labels);border:1px solid var(--color-borders-and-icons-stroke-shape);"><th>Заголовок 1</th><th>Заголовок 2</th><th>Заголовок 3</th></tr><tr style="background-color:var(--color-background-widget-headers);border:1px solid var(--color-borders-and-icons-widget-strokes);"><td>Значение 1</td><td>Значение 2</td><td>Значение 3</td></tr><tr style="background-color:var(--color-background-popup-widgets);border:1px solid var(--color-borders-and-icons-stroke-shape);"><td>Значение 4</td><td>Значение 5</td><td>Значение 6</td></tr><tr style="background-color:var(--color-background-widget-headers);border:1px solid var(--color-borders-and-icons-widget-strokes);"><td>Значение 7</td><td>Значение 8</td><td>Значение 9</td></tr><tr style="background-color:var(--color-background-popup-widgets);border:1px solid var(--color-borders-and-icons-stroke-shape);"><td>Значение 10</td><td>Значение 11</td><td>Значение 12</td></tr></table>',
        width: 280,
        height: 160,
        searchLabel: 'HTML таблица HTML Table جدول HTML tableHtml',
      },
      {
        name: 'tableHtml',
        shape: 'text;html=1;strokeColor=#c0c0c0;fillColor=none;overflow=fill;',
        cellType: ShapeTypeEnum.HtmlShape,
        value:
          '<table border="0" width="100%" height="100%" style="width:100%;height:100%;border-collapse:collapse;"><tr><td align="center">Значение 1</td><td align="center">Значение 2</td><td align="center">Значение 3</td></tr><tr><td align="center">Значение 4</td><td align="center">Значение 5</td><td align="center">Значение 6</td></tr><tr><td align="center">Значение 7</td><td align="center">Значение 8</td><td align="center">Значение 9</td></tr></table>',
        width: 180,
        height: 140,
        searchLabel: 'HTML таблица HTML Table جدول HTML tableHtml',
      },
      {
        name: 'tableHtml',
        shape: 'text;html=1;strokeColor=none;fillColor=none;overflow=fill;',
        cellType: ShapeTypeEnum.HtmlShape,
        value:
          '<table border="1" width="100%" height="100%" style="width:100%;height:100%;border-collapse:collapse;"><tr><td align="center">Значение 1</td><td align="center">Значение 2</td><td align="center">Значение 3</td></tr><tr><td align="center">Значение 4</td><td align="center">Значение 5</td><td align="center">Значение 6</td></tr><tr><td align="center">Значение 7</td><td align="center">Значение 8</td><td align="center">Значение 9</td></tr></table>',
        width: 180,
        height: 140,
        searchLabel: 'HTML таблица HTML Table جدول HTML tableHtml',
      },
      {
        name: 'tableHtml',
        shape: 'text;html=1;strokeColor=none;fillColor=none;overflow=fill;',
        cellType: ShapeTypeEnum.HtmlShape,
        value:
          '<table border="1" width="100%" height="100%" cellpadding="4" style="width:100%;height:100%;border-collapse:collapse;"><tr><th align="center"><b>Заголовок</b></th></tr><tr><td align="center">Раздел 1.1\nРаздел 1.2\nРаздел 1.3</td></tr><tr><td align="center">Раздел 2.1\nРаздел 2.2\nРаздел 2.3</td></tr></table>',
        width: 180,
        height: 140,
        searchLabel: 'HTML таблица HTML Table جدول HTML tableHtml',
      },
    ],
  },
];

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const OM_SHAPES: IShapeItemGroup[] = [
  {
    name: 'omTree',
    shapes: [
      {
        name: 'omShape',
        pathToImg: 'basic/om-shape.svg',
        shape: 'om-shape',
        cellType: ShapeTypeEnum.OmShapeUnset,
        searchLabel: 'Шейп объектной модели Object model shape شکل مدل شی omShape',
      },
      {
        name: 'omShapeCollapsed',
        pathToImg: 'basic/om-shape-collapsed.svg',
        shape: 'om-shape-collapsed',
        cellType: ShapeTypeEnum.OmShapeUnset,
        searchLabel: 'Шейп объектной модели Object model shape شکل مدل شی omShape',
      },
    ],
  },
];

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const OLD_SHAPES: IShapeItemGroup[] = [
  {
    name: 'figures',
    shapes: [
      {
        name: 'verticalColumn',
        pathToImg: 'figures/default/shape1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Вертикальная колонна Vertical column ستون عمودی verticalColumn',
      },
      {
        name: 'rectangle',
        pathToImg: 'figures/default/shape2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Прямоугольник Rectangle مستطیل rectangle',
      },
      {
        name: 'bake',
        pathToImg: 'figures/default/shape4.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Печь Bake پختن bake',
      },
      {
        name: 'pump',
        pathToImg: 'figures/default/shape5.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Насос Pump پمپ pump',
      },
      {
        name: 'gateValve',
        pathToImg: 'figures/default/shape6.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка Gate دروازه gateValve',
      },
      {
        name: 'cooler',
        pathToImg: 'figures/default/shape7.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Кулер Cooler خنک کننده cooler',
      },
      {
        name: 'figure9',
        pathToImg: 'figures/default/shape9.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Фигура 9 Figure 9 شکل 9 figure9',
      },
      {
        name: 'figureType1',
        pathToImg: 'other/default/other-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Фигура тип 1 Figure type 1 شکل نوع 1 figureType1',
      },
      {
        name: 'figureType2',
        pathToImg: 'other/default/other-2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Фигура тип 2 Figure type 2 شکل نوع 2 figureType2',
      },
      {
        name: 'figureType3',
        pathToImg: 'other/default/other-3.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Фигура тип 3 Figure type 3 3 figureType3',
      },
    ],
  },
  {
    name: 'pipes',
    shapes: [
      {
        name: 'pipe1',
        pathToImg: 'pipes/default/pipe-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Труба Pipe لوله pipe1',
      },
      {
        name: 'pipeAngleType1',
        pathToImg: 'pipes/default/pipe-corner-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Труба , угол тип 1 Pipe angle type 1 زاویه لوله نوع 1 pipeAngleType1',
      },
      {
        name: 'pipeAngleType2',
        pathToImg: 'pipes/default/pipe-corner-2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Труба , угол тип 2 Pipe angle type 2 زاویه لوله نوع 2 pipeAngleType2',
      },
    ],
  },
  {
    name: 'tanks',
    shapes: [
      {
        name: 'horizontalTank',
        pathToImg: 'tanks/default/shape3.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Горизонтальный резервуар Horizontal tank مخزن افقی horizontalTank',
      },
      {
        name: 'verticalTank',
        pathToImg: 'tanks/default/shape8.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Вертикальный резервуар Vertical tank مخزن عمودی verticalTank',
      },
      {
        name: 'tankType1',
        pathToImg: 'tanks/default/tank-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Резервуар тип 1 Tank type 1 تانک نوع 1 tankType1',
      },
    ],
  },
  {
    name: 'heaters',
    shapes: [
      {
        name: 'heaterType1',
        pathToImg: 'heating/default/heating-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Нагреватель тип 1 Heater type 1 بخاری نوع 1 heaterType1',
      },
      {
        name: 'heaterType2',
        pathToImg: 'heating/default/heating-2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Нагреватель тип 2 Heater type 2 بخاری نوع 2 heaterType2',
      },
    ],
  },
  {
    name: 'pumps',
    shapes: [
      {
        name: 'pumpType1',
        pathToImg: 'pumps/default/pump-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Насос тип 1 Pump type 1 پمپ نوع 1 pumpType1',
      },
      {
        name: 'pumpType2',
        pathToImg: 'pumps/default/pump-2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Насос тип 2 Pump type 2 پمپ نوع 2 pumpType2',
      },
    ],
  },
  {
    name: 'transport',
    shapes: [
      {
        name: 'tankTruck',
        pathToImg: 'transport/default/shape10.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Автоцистерна Tank truck کامیون تانک tankTruck',
      },
      {
        name: 'railwayCistern',
        pathToImg: 'transport/default/shape11.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'ЖД Цистерна Railway cistern مخزن راه آهن railwayCistern',
      },
      {
        name: 'bunkerer',
        pathToImg: 'transport/default/shape12.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Бункеровщик bunkerer پناهگاه bunkerer',
      },
    ],
  },
  {
    name: 'valves',
    shapes: [
      {
        name: 'valveType1',
        pathToImg: 'valves/default/valve-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 1 Valve type 1 شیر نوع 1 valveType1',
      },
      {
        name: 'valveType2',
        pathToImg: 'valves/default/valve-2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 2 Valve type 2 شیر نوع 2 valveType2',
      },
      {
        name: 'valveType3',
        pathToImg: 'valves/default/valve-3.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 3 Valve type 3 شیر نوع 3 valveType3',
      },
      {
        name: 'valveType4',
        pathToImg: 'valves/default/valve-4.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 4 Valve type 4 شیر نوع 4 valveType4',
      },
      {
        name: 'valveType5',
        pathToImg: 'valves/default/valve-5.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 5 Valve type 5 شیر نوع 5 valveType5',
      },
      {
        name: 'valveType6',
        pathToImg: 'valves/default/valve-6.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 6 Valve type 6 شیر نوع 6 valveType6',
      },
      {
        name: 'valveType7',
        pathToImg: 'valves/default/valve-7.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 7 Valve type 7 شیر نوع 7 valveType7',
      },
      {
        name: 'valveType8',
        pathToImg: 'valves/default/valve-8.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 8 Valve type 8 شیر نوع 8 valveType8',
      },
      {
        name: 'valveType9',
        pathToImg: 'valves/default/valve-9.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Задвижка тип 9 Valve type 9 شیر نوع 9 valveType9',
      },
    ],
  },
  {
    name: 'columns',
    shapes: [
      {
        name: 'columnType1',
        pathToImg: 'columns/default/column-1.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 1 Column type 1 ستون نوع 1 columnType1',
      },
      {
        name: 'columnType2',
        pathToImg: 'columns/default/column-2.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 2 Column type 2 ستون نوع 2 columnType2',
      },
      {
        name: 'columnType3',
        pathToImg: 'columns/default/column-3.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 3 Column type 3 ستون نوع 3 columnType3',
      },
      {
        name: 'columnType4',
        pathToImg: 'columns/default/column-4.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 4 Column type 4 ستون نوع 4 columnType4',
      },
      {
        name: 'columnType5',
        pathToImg: 'columns/default/column-5.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 5 Column type 5 ستون نوع 5 columnType5',
      },
      {
        name: 'columnType6',
        pathToImg: 'columns/default/column-6.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 6 Column type 6 ستون نوع 6 columnType6',
      },
      {
        name: 'columnType7',
        pathToImg: 'columns/default/column-7.svg',
        shape: 'image',
        cellType: ShapeTypeEnum.Svg,
        searchLabel: 'Колонна тип 7 Column type 7 ستون نوع 7 columnType7',
      },
    ],
  },
];

export const MNEMO_SHAPES: IShapeItemGroup[] = [
  ...GEOMETRY_SHAPES,
  ...OLD_SHAPES,
  ...IMPORTED_SHAPES.sort((a, b) => sortByNameFunction(a, b)),
] as IShapeItemGroup[];

export const GET_MNEMO_SHAPES_SORT_TRANSLATED = (translocoService: {
  translate(t: string): string;
}): IShapeItemGroup[] => {
  return [
    ...GEOMETRY_SHAPES,
    ...OLD_SHAPES,
    ...IMPORTED_SHAPES.sort((a, b) =>
      translocoService.translate(`shapes.${a.name}`) >= translocoService.translate(`shapes.${b.name}`) ? 1 : -1
    ),
  ] as IShapeItemGroup[];
};

// export const MNEMO_ACTIVE_SHAPES: IShapeItemGroup[] = [
//   {
//     name: 'activeElement',
//     shapes: ACTIVE_SHAPES.filter((v) => v.isMnemoItem).map((item) => {
//       const element: IShapeItem = {
//         name: item.name,
//         pathToImg: `active/${item.icon}`,
//         shape: 'rectangle',
//         cellType: ShapeTypeEnum.ActiveElement,
//         viewElementType: item.type,
//         dataItemType: item.dataItemType ?? DataItemTypeEnum.Null,
//       };
//       return element;
//     }),
//   },
// ];
